import type { SuperAdminPageProps } from "./types";
import { useSuperAdminSharedContext } from "./state/shared";
import { useSuperAdminOverviewState } from "./state/useSuperAdminOverviewState";
import { useSuperAdminTierState } from "./state/useSuperAdminTierState";
import { useSuperAdminRequestsState } from "./state/useSuperAdminRequestsState";
import { useSuperAdminManageTenantState } from "./state/useSuperAdminManageTenantState";
import { useSuperAdminRolesState } from "./state/useSuperAdminRolesState";
import { useSuperAdminSystemUsersState } from "./state/useSuperAdminSystemUsersState";

export function useSuperAdminPageState(props: SuperAdminPageProps) {
  const {
    tenantForm,
    onTenantFormChange,
    creatingTenant,
    onRefreshAdminRequests,
    onRefreshSystemUsers,
    subscriptionRequests,
    pendingPharmacyLoginAccounts,
    pendingPharmacySignupRequests,
    pendingCustomRoles,
    selectedPharmacyId,
    onSelectPharmacy,
    onSwitchTenant,
    onOpenTenantUsers,
    onResetTenantForm,
    onCreateTenant,
    onCreateOrganizationBranch,
    onUpdateOrganizationBranch,
    onDeleteOrganization,
    onDeleteOrganizationBranch,
    onUpdateTenantStatus,
    onUpdateMaxBranches,
    onUpdateMaxUsers,
    onUpdateOrganizationFreeTrial,
    onUpdateSubscriptionTier,
    onRefreshPharmacies,
  } = props;

  const shared = useSuperAdminSharedContext(props);

  const overview = useSuperAdminOverviewState({
    isArabic: shared.isArabic,
    pharmacies: shared.pharmacies,
    subscriptionRequests,
    pendingPharmacyLoginAccounts,
    pendingPharmacySignupRequests,
    pendingCustomRoles,
  });

  const manage = useSuperAdminManageTenantState({
    isArabic: shared.isArabic,
    pharmacies: shared.pharmacies,
    selected: shared.selected,
    selectedBranchUsage: shared.selectedBranchUsage,
    selectedOrgBranches: shared.selectedOrgBranches,
    selectedOrgBranchIds: shared.selectedOrgBranchIds,
    expandedOrgIds: overview.expandedOrgIds,
    setExpandedOrgIds: overview.setExpandedOrgIds,
    selectedPharmacyId,
    onSelectPharmacy,
    onSwitchTenant,
    onOpenTenantUsers,
    onResetTenantForm,
    onCreateTenant,
    onCreateOrganizationBranch,
    onUpdateOrganizationBranch,
    onDeleteOrganization,
    onDeleteOrganizationBranch,
    onUpdateTenantStatus,
  });

  const tier = useSuperAdminTierState({
    isArabic: shared.isArabic,
    operatorUid: shared.operatorUid,
    pharmacies: shared.pharmacies,
    systemUsers: shared.systemUsers,
    selected: shared.selected,
    selectedTierCap: shared.selectedTierCap,
    activeTab: overview.activeTab,
    manageModalOpen: manage.manageModalOpen,
    setActiveTab: overview.setActiveTab,
    setManageModalOpen: manage.setManageModalOpen,
    onUpdateSubscriptionTier,
    onUpdateMaxBranches,
    onUpdateMaxUsers,
    onUpdateOrganizationFreeTrial,
    onRefreshPharmacies,
  });

  const requests = useSuperAdminRequestsState({
    isArabic: shared.isArabic,
    pharmacies: shared.pharmacies,
    onApproveSubscriptionRequest: props.onApproveSubscriptionRequest,
    onRejectSubscriptionRequest: props.onRejectSubscriptionRequest,
    onApprovePharmacyLoginAccount: props.onApprovePharmacyLoginAccount,
    onRejectPharmacyLoginAccount: props.onRejectPharmacyLoginAccount,
    onApprovePharmacySignupRequest: props.onApprovePharmacySignupRequest,
    onRejectPharmacySignupRequest: props.onRejectPharmacySignupRequest,
    onRefreshAdminRequests,
  });

  const roles = useSuperAdminRolesState({
    isArabic: shared.isArabic,
    pharmacies: shared.pharmacies,
    selected: shared.selected,
    activeTab: overview.activeTab,
    manageModalOpen: manage.manageModalOpen,
    reloadManageRoles: manage.reloadManageRoles,
    onRefreshSystemUsers,
  });

  const systemUsersState = useSuperAdminSystemUsersState({
    isArabic: shared.isArabic,
    operatorUid: shared.operatorUid,
    selected: shared.selected,
    selectedOrgBranches: shared.selectedOrgBranches,
    manageCustomRoles: manage.manageCustomRoles,
    manageRoleConfigs: manage.manageRoleConfigs,
    manageEmployees: manage.manageEmployees,
    manageLoginAccounts: manage.manageLoginAccounts,
    manageOrgSystemUsers: manage.manageOrgSystemUsers,
    manageRoleAccountDisplayRows: manage.manageRoleAccountDisplayRows,
    canPickSystemUserBranch: manage.canPickSystemUserBranch,
    reloadManageRoles: manage.reloadManageRoles,
    resolveBuiltinRoleLabels: manage.resolveBuiltinRoleLabels,
    onRefreshSystemUsers,
  });

  return {
    isArabic: shared.isArabic,
    operatorUid: shared.operatorUid,
    pharmacies: shared.pharmacies,
    systemUsers: shared.systemUsers,
    selectedPharmacyId,
    tenantForm,
    onTenantFormChange,
    creatingTenant,
    onRefreshAdminRequests,
    onRefreshSystemUsers,
    subscriptionRequests,
    pendingPharmacyLoginAccounts,
    pendingCustomRoles,
    pendingPharmacySignupRequests,
    addModalOpen: manage.addModalOpen,
    setAddModalOpen: manage.setAddModalOpen,
    manageModalOpen: manage.manageModalOpen,
    setManageModalOpen: manage.setManageModalOpen,
    branchModalMode: manage.branchModalMode,
    branchForm: manage.branchForm,
    setBranchForm: manage.setBranchForm,
    creatingBranch: manage.creatingBranch,
    deletingBranchId: manage.deletingBranchId,
    manageRolesLoading: manage.manageRolesLoading,
    manageCustomRoles: manage.manageCustomRoles,
    manageRoleConfigs: manage.manageRoleConfigs,
    manageEmployees: manage.manageEmployees,
    manageLoginAccounts: manage.manageLoginAccounts,
    manageOrgSystemUsers: manage.manageOrgSystemUsers,
    roleModalOpen: roles.roleModalOpen,
    roleForm: roles.roleForm,
    setRoleForm: roles.setRoleForm,
    savingRole: roles.savingRole,
    deletingRoleId: roles.deletingRoleId,
    systemUserModalOpen: systemUsersState.systemUserModalOpen,
    systemUserModalMode: systemUsersState.systemUserModalMode,
    editingSystemUserUid: systemUsersState.editingSystemUserUid,
    systemUserForm: systemUsersState.systemUserForm,
    setSystemUserForm: systemUsersState.setSystemUserForm,
    savingSystemUser: systemUsersState.savingSystemUser,
    systemUserBusyUid: systemUsersState.systemUserBusyUid,
    showSystemUserPassword: systemUsersState.showSystemUserPassword,
    setShowSystemUserPassword: systemUsersState.setShowSystemUserPassword,
    statusTarget: manage.statusTarget,
    setStatusTarget: manage.setStatusTarget,
    statusUpdating: manage.statusUpdating,
    deleteTarget: manage.deleteTarget,
    setDeleteTarget: manage.setDeleteTarget,
    deleteUpdating: manage.deleteUpdating,
    tierEditModalOpen: tier.tierEditModalOpen,
    editingTierId: tier.editingTierId,
    tierEditForm: tier.tierEditForm,
    setTierEditForm: tier.setTierEditForm,
    tierConfigVersion: tier.tierConfigVersion,
    savingTierConfig: tier.savingTierConfig,
    selected: shared.selected,
    selectedBranchUsage: shared.selectedBranchUsage,
    selectedUserUsage: shared.selectedUserUsage,
    selectedOrgBranches: shared.selectedOrgBranches,
    selectedTier: shared.selectedTier,
    selectedTierCap: shared.selectedTierCap,
    selectedTrialStatus: shared.selectedTrialStatus,
    freeTrialDraft: tier.freeTrialDraft,
    setFreeTrialDraft: tier.setFreeTrialDraft,
    freeTrialSavingId: tier.freeTrialSavingId,
    activeTab: overview.activeTab,
    setActiveTab: overview.setActiveTab,
    customerRequestFilter: overview.customerRequestFilter,
    setCustomerRequestFilter: overview.setCustomerRequestFilter,
    expandedOrgIds: overview.expandedOrgIds,
    rolesReferenceLoading: roles.rolesReferenceLoading,
    rolesReferenceQuery: roles.rolesReferenceQuery,
    setRolesReferenceQuery: roles.setRolesReferenceQuery,
    pendingCustomerRequestsCount: overview.pendingCustomerRequestsCount,
    pharmacyNameById: overview.pharmacyNameById,
    requestUpdating: requests.requestUpdating,
    signupApproveTarget: requests.signupApproveTarget,
    signupApproveTier: requests.signupApproveTier,
    setSignupApproveTier: requests.setSignupApproveTier,
    closeSignupApproveModal: requests.closeSignupApproveModal,
    confirmSignupApprove: requests.confirmSignupApprove,
    maxBranchSavingId: tier.maxBranchSavingId,
    maxUserSavingId: tier.maxUserSavingId,
    tierSavingId: tier.tierSavingId,
    maxBranchDrafts: tier.maxBranchDrafts,
    setMaxBranchDrafts: tier.setMaxBranchDrafts,
    maxUserDrafts: tier.maxUserDrafts,
    setMaxUserDrafts: tier.setMaxUserDrafts,
    saasTabs: overview.saasTabs,
    customerRequestRows: overview.customerRequestRows,
    pharmacyOrgGroups: overview.pharmacyOrgGroups,
    filteredProgramRoleListRows: roles.filteredProgramRoleListRows,
    manageUnifiedRoleRows: manage.manageUnifiedRoleRows,
    manageRoleAccountDisplayRows: manage.manageRoleAccountDisplayRows,
    manageUnifiedRolesTableColSpan: manage.manageUnifiedRolesTableColSpan,
    manageOrphanSystemUsers: systemUsersState.manageOrphanSystemUsers,
    manageEmployeeById: manage.manageEmployeeById,
    manageRoleSelectEntries: systemUsersState.manageRoleSelectEntries,
    canPickSystemUserBranch: manage.canPickSystemUserBranch,
    operatorAppUser: systemUsersState.operatorAppUser,
    reloadRolesReference: roles.reloadRolesReference,
    reloadManageRoles: manage.reloadManageRoles,
    openTierEditModal: tier.openTierEditModal,
    closeTierEditModal: tier.closeTierEditModal,
    submitTierEdit: tier.submitTierEdit,
    handleTierChange: tier.handleTierChange,
    getMaxBranchDraft: tier.getMaxBranchDraft,
    getMaxUserDraft: tier.getMaxUserDraft,
    saveFreeTrial: tier.saveFreeTrial,
    saveMaxUsers: tier.saveMaxUsers,
    applyTierWarehouseLimit: tier.applyTierWarehouseLimit,
    saveMaxBranches: tier.saveMaxBranches,
    handleApproveRequest: requests.handleApproveRequest,
    handleRejectRequest: requests.handleRejectRequest,
    handleApproveLoginRequest: requests.handleApproveLoginRequest,
    handleRejectLoginRequest: requests.handleRejectLoginRequest,
    handleApproveSignupRequest: requests.handleApproveSignupRequest,
    handleRejectSignupRequest: requests.handleRejectSignupRequest,
    handleApproveRoleRequest: requests.handleApproveRoleRequest,
    handleRejectRoleRequest: requests.handleRejectRoleRequest,
    openManage: manage.openManage,
    closeAddModal: manage.closeAddModal,
    submitCreateTenant: manage.submitCreateTenant,
    openAddBranchModal: manage.openAddBranchModal,
    openEditBranchModal: manage.openEditBranchModal,
    closeBranchModal: manage.closeBranchModal,
    submitBranchForm: manage.submitBranchForm,
    deleteBranch: manage.deleteBranch,
    openAddRoleModal: roles.openAddRoleModal,
    openEditBuiltinRole: roles.openEditBuiltinRole,
    tryDeleteBuiltinRole: roles.tryDeleteBuiltinRole,
    openEditRoleModal: roles.openEditRoleModal,
    closeRoleModal: roles.closeRoleModal,
    handleOpenEmployeesPage: manage.handleOpenEmployeesPage,
    saveRoleForm: roles.saveRoleForm,
    activateCustomRole: roles.activateCustomRole,
    deleteCustomRole: roles.deleteCustomRole,
    openAddSystemUserModal: systemUsersState.openAddSystemUserModal,
    openEditSystemUserModal: systemUsersState.openEditSystemUserModal,
    closeSystemUserModal: systemUsersState.closeSystemUserModal,
    saveSystemUserForm: systemUsersState.saveSystemUserForm,
    deleteSystemUserRow: systemUsersState.deleteSystemUserRow,
    confirmStatusChange: manage.confirmStatusChange,
    confirmDelete: manage.confirmDelete,
    handleViewAsTenant: manage.handleViewAsTenant,
    formatEndDateAfterApproval: requests.formatEndDateAfterApproval,
    getCustomerRequestResult: requests.getCustomerRequestResult,
    isCustomerRequestBusy: requests.isCustomerRequestBusy,
    toggleOrgExpanded: overview.toggleOrgExpanded,
    openPackagesTabFromManage: tier.openPackagesTabFromManage,
  };
}

export type SuperAdminPageState = ReturnType<typeof useSuperAdminPageState>;
