import type { EmployeesUsersPageProps } from "./types";
import { staffActionErrorMessage } from "./helpers";
import { useStaffSharedContext, useStaffSharedDerived } from "./state/shared";
import { useStaffDataState } from "./state/useStaffDataState";
import { useStaffLoginCatalogState } from "./state/useStaffLoginCatalogState";
import { useStaffPermissionsState } from "./state/useStaffPermissionsState";
import { useStaffEmployeesState } from "./state/useStaffEmployeesState";

export function useEmployeesUsersPageState(props: EmployeesUsersPageProps) {
  const shared = useStaffSharedContext(props);

  const data = useStaffDataState({
    appUser: shared.appUser,
    pharmacyId: shared.pharmacyId,
    loadOrgEmployeeScope: shared.loadOrgEmployeeScope,
    shouldLoadLoginCatalog: shared.shouldLoadLoginCatalog,
    orgBranchIds: shared.orgBranchIds,
    canViewLoginAccountsTab: shared.canViewLoginAccountsTab,
    setLoading: shared.setLoading,
    setLoadError: shared.setLoadError,
  });

  const derived = useStaffSharedDerived({
    isArabic: shared.isArabic,
    appUser: shared.appUser,
    pharmacyId: shared.pharmacyId,
    tenantScopePharmacyId: shared.tenantScopePharmacyId,
    showOrgHr: shared.showOrgHr,
    canFilterEmployeesByBranch: shared.canFilterEmployeesByBranch,
    isTenantScopedView: shared.isTenantScopedView,
    orgBranchIds: shared.orgBranchIds,
    employeeBranchFilter: shared.employeeBranchFilter,
    loginAccountsPanelBranchFilter: shared.loginAccountsPanelBranchFilter,
    branchDirectory: shared.branchDirectory,
    pharmacies: shared.pharmacies,
    employees: data.employees,
    loginCatalog: data.loginCatalog,
    systemUsers: data.systemUsers,
  });

  const loginCatalog = useStaffLoginCatalogState({
    isArabic: shared.isArabic,
    appUser: shared.appUser,
    pharmacyId: shared.pharmacyId,
    tenantScopePharmacyId: shared.tenantScopePharmacyId,
    currentUid: shared.currentUid,
    onActivityLog: shared.onActivityLog,
    canViewLoginAccountsTab: shared.canViewLoginAccountsTab,
    canManageLoginAccountsCatalog: shared.canManageLoginAccountsCatalog,
    branchDirectory: shared.branchDirectory,
    orgBranchIds: shared.orgBranchIds,
    catalogBranchFilter: shared.catalogBranchFilter,
    setCatalogBranchFilter: shared.setCatalogBranchFilter,
    employeeBranchFilter: shared.employeeBranchFilter,
    loginAccountsPanelBranchFilter: shared.loginAccountsPanelBranchFilter,
    setLoginAccountsPanelBranchFilter: shared.setLoginAccountsPanelBranchFilter,
    setEmployeesAccessPanel: shared.setEmployeesAccessPanel,
    busy: shared.busy,
    setBusy: shared.setBusy,
    employeeById: derived.employeeById,
    generalManagerScope: derived.generalManagerScope,
    employeesPanelPharmacyId: derived.employeesPanelPharmacyId,
    loginCatalog: data.loginCatalog,
    customRoles: data.customRoles,
    systemUsers: data.systemUsers,
    orgUserUsage: derived.orgUserUsage,
    loadAll: data.loadAll,
    refreshLoginCatalog: data.refreshLoginCatalog,
  });

  const permissions = useStaffPermissionsState({
    isArabic: shared.isArabic,
    appUser: shared.appUser,
    currentUid: shared.currentUid,
    setBusy: shared.setBusy,
    catalogByEmployeeId: derived.catalogByEmployeeId,
    customRoles: data.customRoles,
    systemUsers: data.systemUsers,
    catalogTargetPharmacyId: loginCatalog.catalogTargetPharmacyId,
    employeesPanelPharmacyId: derived.employeesPanelPharmacyId,
    loadAll: data.loadAll,
    openCatalogAccountAdd: loginCatalog.openCatalogAccountAdd,
  });

  const employees = useStaffEmployeesState({
    isArabic: shared.isArabic,
    appUser: shared.appUser,
    pharmacyId: shared.pharmacyId,
    pharmacies: shared.pharmacies,
    onActivityLog: shared.onActivityLog,
    showOrgHrManage: shared.showOrgHrManage,
    canManage: shared.canManage,
    canViewLoginAccountsTab: shared.canViewLoginAccountsTab,
    busy: shared.busy,
    setBusy: shared.setBusy,
    branchLabel: shared.branchLabel,
    employeeById: derived.employeeById,
    catalogByEmployeeId: derived.catalogByEmployeeId,
    generalManagerScope: derived.generalManagerScope,
    loginCatalogByPharmacy: derived.loginCatalogByPharmacy,
    loginCatalog: data.loginCatalog,
    customRoles: data.customRoles,
    systemUsers: data.systemUsers,
    loadAll: data.loadAll,
    syncSavedCatalogAccount: loginCatalog.syncSavedCatalogAccount,
    branchCustomRoles: loginCatalog.branchCustomRoles,
  });

  return {
    isArabic: shared.isArabic,
    appUser: shared.appUser,
    pharmacyId: shared.pharmacyId,
    pharmacies: shared.pharmacies,
    tenantScopePharmacyId: shared.tenantScopePharmacyId,
    currency: shared.currency,
    currentUid: shared.currentUid,
    onActivityLog: shared.onActivityLog,
    onOpenSubscriptionSettings: shared.onOpenSubscriptionSettings,
    isAccountantOnly: shared.isAccountantOnly,
    activeTab: shared.activeTab,
    setActiveTab: shared.setActiveTab,
    employees: data.employees,
    loginCatalog: data.loginCatalog,
    customRoles: data.customRoles,
    roleConfigs: data.roleConfigs,
    permissionEditorTarget: permissions.permissionEditorTarget,
    setPermissionEditorTarget: permissions.setPermissionEditorTarget,
    permissionEditorPages: permissions.permissionEditorPages,
    setPermissionEditorPages: permissions.setPermissionEditorPages,
    permissionEditorPermissions: permissions.permissionEditorPermissions,
    setPermissionEditorPermissions: permissions.setPermissionEditorPermissions,
    systemUsers: data.systemUsers,
    activityLogs: data.activityLogs,
    loading: shared.loading,
    busy: shared.busy,
    setBusy: shared.setBusy,
    loadError: shared.loadError,
    employeeModal: employees.employeeModal,
    setEmployeeModal: employees.setEmployeeModal,
    attendanceBadgeEmployee: employees.attendanceBadgeEmployee,
    setAttendanceBadgeEmployee: employees.setAttendanceBadgeEmployee,
    editEmployeeId: employees.editEmployeeId,
    setEditEmployeeId: employees.setEditEmployeeId,
    employeeForm: employees.employeeForm,
    setEmployeeForm: employees.setEmployeeForm,
    pharmacyShifts: employees.pharmacyShifts,
    pharmacyDefaultShiftId: employees.pharmacyDefaultShiftId,
    accountModal: loginCatalog.accountModal,
    setAccountModal: loginCatalog.setAccountModal,
    editCatalogId: loginCatalog.editCatalogId,
    setEditCatalogId: loginCatalog.setEditCatalogId,
    catalogForm: loginCatalog.catalogForm,
    setCatalogForm: loginCatalog.setCatalogForm,
    customRoleModal: permissions.customRoleModal,
    setCustomRoleModal: permissions.setCustomRoleModal,
    customRoleRequestMode: permissions.customRoleRequestMode,
    setCustomRoleRequestMode: permissions.setCustomRoleRequestMode,
    employeesAccessPanel: shared.employeesAccessPanel,
    setEmployeesAccessPanel: shared.setEmployeesAccessPanel,
    loginAccountsPanelBranchFilter: shared.loginAccountsPanelBranchFilter,
    setLoginAccountsPanelBranchFilter: shared.setLoginAccountsPanelBranchFilter,
    branchHrSummaryOpen: shared.branchHrSummaryOpen,
    setBranchHrSummaryOpen: shared.setBranchHrSummaryOpen,
    transferEmployee: employees.transferEmployee,
    setTransferEmployee: employees.setTransferEmployee,
    transferTargetBranchId: employees.transferTargetBranchId,
    setTransferTargetBranchId: employees.setTransferTargetBranchId,
    customRoleForm: permissions.customRoleForm,
    setCustomRoleForm: permissions.setCustomRoleForm,
    customRoleTemplateOptions: permissions.customRoleTemplateOptions,
    canManage: shared.canManage,
    canManageRolePermissions: shared.canManageRolePermissions,
    canManageRolesOnEmployeesPage: shared.canManageRolesOnEmployeesPage,
    employeeById: derived.employeeById,
    pendingCatalogAccounts: derived.pendingCatalogAccounts,
    isOrgManager: shared.isOrgManager,
    isTenantScopedView: shared.isTenantScopedView,
    branchDirectory: shared.branchDirectory,
    orgTier: shared.orgTier,
    orgUserUsage: derived.orgUserUsage,
    showOrgHrManage: shared.showOrgHrManage,
    showOrgHr: shared.showOrgHr,
    showEmployeesBranchColumn: shared.showEmployeesBranchColumn,
    canFilterEmployeesByBranch: shared.canFilterEmployeesByBranch,
    orgHrReadOnly: shared.orgHrReadOnly,
    hrManagePharmacyId: shared.hrManagePharmacyId,
    canViewLoginAccountsTab: shared.canViewLoginAccountsTab,
    canManageLoginAccountsCatalog: shared.canManageLoginAccountsCatalog,
    canRequestLoginAccounts: shared.canRequestLoginAccounts,
    canShowEmployeesAccessPanels: shared.canShowEmployeesAccessPanels,
    shouldLoadLoginCatalog: shared.shouldLoadLoginCatalog,
    loadOrgEmployeeScope: shared.loadOrgEmployeeScope,
    centralHrUpgradeNotice: shared.centralHrUpgradeNotice,
    orgBranchIds: shared.orgBranchIds,
    employeeBranchFilter: shared.employeeBranchFilter,
    setEmployeeBranchFilter: shared.setEmployeeBranchFilter,
    catalogBranchFilter: shared.catalogBranchFilter,
    setCatalogBranchFilter: shared.setCatalogBranchFilter,
    isCatalogOwner: shared.isCatalogOwner,
    catalogTargetPharmacyId: loginCatalog.catalogTargetPharmacyId,
    branchLoginCatalog: loginCatalog.branchLoginCatalog,
    catalogByEmployeeId: derived.catalogByEmployeeId,
    branchCustomRoles: loginCatalog.branchCustomRoles,
    employeesPanelPharmacyId: derived.employeesPanelPharmacyId,
    employeesPanelLoginAccounts: loginCatalog.employeesPanelLoginAccounts,
    employeesPanelAccessUsers: loginCatalog.employeesPanelAccessUsers,
    loginCatalogByEmail: derived.loginCatalogByEmail,
    generalManagerScope: derived.generalManagerScope,
    loginAccountRoleSelectOptions: loginCatalog.loginAccountRoleSelectOptions,
    systemUserByEmail: derived.systemUserByEmail,
    loginCatalogByPharmacy: derived.loginCatalogByPharmacy,
    pharmacyName: shared.pharmacyName,
    branchLabel: shared.branchLabel,
    branchHrSummaryRows: derived.branchHrSummaryRows,
    filteredEmployees: derived.filteredEmployees,
    loadAll: data.loadAll,
    refreshLoginCatalog: data.refreshLoginCatalog,
    staffActivity: data.staffActivity,
    tabs: shared.tabs,
    isHrTab: shared.isHrTab,
    permissionsBranchCustomRoles: permissions.permissionsBranchCustomRoles,
    hasRole: shared.hasRole,
    approveCatalogAccount: loginCatalog.approveCatalogAccount,
    approveCatalogEdit: loginCatalog.approveCatalogEdit,
    approveCatalogLink: loginCatalog.approveCatalogLink,
    unlinkCatalogAccount: loginCatalog.unlinkCatalogAccount,
    openAddEmployee: employees.openAddEmployee,
    openEditEmployee: employees.openEditEmployee,
    updateEmployeeWorkSchedule: employees.updateEmployeeWorkSchedule,
    saveEmployee: employees.saveEmployee,
    openTransferEmployeeModal: employees.openTransferEmployeeModal,
    confirmTransferEmployee: employees.confirmTransferEmployee,
    deleteEmployeeRecord: employees.deleteEmployeeRecord,
    toggleEmployeeActive: employees.toggleEmployeeActive,
    openCustomRoleModal: permissions.openCustomRoleModal,
    openLoginAccountsPanel: loginCatalog.openLoginAccountsPanel,
    openLoginAccountRequestFromEmployeesPanel: loginCatalog.openLoginAccountRequestFromEmployeesPanel,
    onCustomRoleBaseChange: permissions.onCustomRoleBaseChange,
    toggleCustomRolePage: permissions.toggleCustomRolePage,
    saveCustomRole: permissions.saveCustomRole,
    openPermissionEditorBuiltin: permissions.openPermissionEditorBuiltin,
    openPermissionEditorCustom: permissions.openPermissionEditorCustom,
    isCurrentAppEmployee: permissions.isCurrentAppEmployee,
    openPermissionEditorForEmployee: permissions.openPermissionEditorForEmployee,
    savePermissionEditor: permissions.savePermissionEditor,
    resetPermissionEditorDefaults: permissions.resetPermissionEditorDefaults,
    resetRolePermissionsToDefaults: permissions.resetRolePermissionsToDefaults,
    deleteCustomRoleDefinition: permissions.deleteCustomRoleDefinition,
    openCatalogAccountAdd: loginCatalog.openCatalogAccountAdd,
    openCatalogAccountEdit: loginCatalog.openCatalogAccountEdit,
    openCatalogAccountDuplicate: loginCatalog.openCatalogAccountDuplicate,
    onCatalogFormRoleChange: loginCatalog.onCatalogFormRoleChange,
    openPasswordChangeRequest: loginCatalog.openPasswordChangeRequest,
    savePasswordChangeRequest: loginCatalog.savePasswordChangeRequest,
    saveCatalogAccount: loginCatalog.saveCatalogAccount,
    deleteCatalogAccount: loginCatalog.deleteCatalogAccount,
    assignEmployeeLoginAccount: employees.assignEmployeeLoginAccount,
    assignEmployeeRole: employees.assignEmployeeRole,
    renderEmployeeRoleCell: employees.renderEmployeeRoleCell,
    assignEmployeeSystemUser: employees.assignEmployeeSystemUser,
    renderEmployeeLoginCell: employees.renderEmployeeLoginCell,
    renderLoginAccountLinkStatus: loginCatalog.renderLoginAccountLinkStatus,
    renderSystemUserStatus: loginCatalog.renderSystemUserStatus,
    getEmployeeAssignedAccountId: employees.getEmployeeAssignedAccountId,
    getEmployeeLinkedUserUid: employees.getEmployeeLinkedUserUid,
    employeeLoginAccountOptionsFor: employees.employeeLoginAccountOptionsFor,
    formatLoginAccountOptionLabel: loginCatalog.formatLoginAccountOptionLabel,
    employeeRoleOptionsFor: employees.employeeRoleOptionsFor,
    getEmployeeSelectedRole: employees.getEmployeeSelectedRole,
    staffActionErrorMessage: (err: unknown, fallback: string) =>
      staffActionErrorMessage(err, shared.isArabic, fallback),
  };
}

export type EmployeesUsersPageState = ReturnType<typeof useEmployeesUsersPageState>;
