const camelKeyMap: Record<string, string> = {
  pharmacy_id: "pharmacyId",
  customer_name: "customerName",
  customer_phone: "customerPhone",
  created_at: "createdAt",
  updated_at: "updatedAt",
  invoice_number: "invoiceNumber",
  invoice_id: "invoiceId",
  payment_method: "paymentMethod",
  cashier_id: "cashierId",
  cashier_name: "cashierName",
  buy_price: "buyPrice",
  sell_price: "sellPrice",
  total_cost: "totalCost",
  total_profit: "totalProfit",
  quantity_change: "quantityChange",
  qty_before: "qtyBefore",
  qty_after: "qtyAfter",
  return_number: "returnNumber",
  purchase_number: "purchaseNumber",
  cost_number: "costNumber",
  original_invoice_id: "originalInvoiceId",
  user_id: "userId",
  user_name: "userName",
  reference_type: "referenceType",
  reference_id: "referenceId",
  is_active: "isActive",
  name_ar: "name_ar",
  name_en: "name_en",
  medicine_id: "medicineId",
  medicine_name_ar: "medicineName_ar",
  medicine_name_en: "medicineName_en",
  medicine_name: "name_ar",
  unit_price: "unitPrice",
  line_total: "lineTotal",
  cost_total: "costTotal",
  movement_type: "type",
  subscription_plan: "subscriptionPlan",
  subscription_status: "subscriptionStatus",
  subscription_started_at: "subscriptionStartedAt",
  subscription_ends_at: "subscriptionEndsAt",
  subscription_end_date: "subscriptionEndDate",
  hold_number: "holdNumber",
  cart_items: "cartItems",
  created_by: "createdBy",
  created_by_name: "createdByName",
  refund_method: "refundMethod",
  is_instant: "isInstant",
  low_stock_threshold: "lowStockThreshold",
  expiring_soon_days: "expiringSoonDays",
  expiry_notify_enabled: "expiryNotifyEnabled",
  expiry_notify_phone: "expiryNotifyPhone",
  expiry_notify_email: "expiryNotifyEmail",
  payroll_pay_day: "payrollPayDay",
  payroll_sick_deduction_percent: "payrollSickDeductionPercent",
  payroll_absent_deduction_percent: "payrollAbsentDeductionPercent",
  payroll_leave_deduction_percent: "payrollLeaveDeductionPercent",
  payroll_max_leave_days: "payrollMaxLeaveDays",
  payroll_standard_work_hours: "payrollStandardWorkHours",
  payroll_overtime_percent: "payrollOvertimePercent",
  payroll_work_day_start: "payrollWorkDayStart",
  payroll_work_day_end: "payrollWorkDayEnd",
  payroll_work_breaks: "payrollWorkBreaks",
  work_shifts: "workShifts",
  default_shift_id: "defaultShiftId",
  assigned_shift_id: "assignedShiftId",
  shift_id: "shiftId",
  cashier_shift_id: "cashierShiftId",
  shift_number: "shiftNumber",
  opening_cash: "openingCash",
  expected_cash: "expectedCash",
  actual_cash: "actualCash",
  cash_variance: "cashVariance",
  cash_sales: "cashSales",
  visa_sales: "visaSales",
  wallet_sales: "walletSales",
  credit_sales: "creditSales",
  returns_total: "returnsTotal",
  customer_payments_cash: "customerPaymentsCash",
  customer_payments_other: "customerPaymentsOther",
  invoice_count: "invoiceCount",
  opened_at: "openedAt",
  closed_at: "closedAt",
  closed_by_id: "closedById",
  closed_by_name: "closedByName",
  work_shift_id: "workShiftId",
  early_leave_outcome: "earlyLeaveOutcome",
  request_number: "requestNumber",
  pharmacy_name: "pharmacyName",
  requested_by: "requestedBy",
  requested_by_name: "requestedByName",
  reviewed_by: "reviewedBy",
  reviewed_by_name: "reviewedByName",
  review_note: "reviewNote",
  reviewed_at: "reviewedAt",
  employee_id: "employeeId",
  employee_code: "employeeCode",
  photo_base64: "photoBase64",
  required_work_hours: "requiredWorkHours",
  use_custom_work_schedule: "useCustomWorkSchedule",
  work_day_start: "workDayStart",
  work_day_end: "workDayEnd",
  work_breaks: "workBreaks",
  employee_name: "employeeName",
  job_title: "jobTitle",
  role_key: "roleKey",
  allowed_pages: "allowedPages",
  base_role: "baseRole",
  commission_rate: "commissionRate",
  hire_date: "hireDate",
  last_login_at: "lastLoginAt",
  request_type: "requestType",
  end_date: "endDate",
  requested_time: "requestedTime",
};

const snakeKeyMap: Record<string, string> = {
  buyPrice: "buy_price",
  sellPrice: "sell_price",
  totalCost: "total_cost",
  totalProfit: "total_profit",
  quantityChange: "quantity_change",
  qtyBefore: "qty_before",
  qtyAfter: "qty_after",
  invoiceNumber: "invoice_number",
  invoiceId: "invoice_id",
  paymentMethod: "payment_method",
  cashierId: "cashier_id",
  cashierName: "cashier_name",
  customerName: "customer_name",
  customerPhone: "customer_phone",
  pharmacyId: "pharmacy_id",
  returnNumber: "return_number",
  purchaseNumber: "purchase_number",
  originalInvoiceId: "original_invoice_id",
  userId: "user_id",
  userName: "user_name",
  referenceType: "reference_type",
  referenceId: "reference_id",
  paymentNumber: "payment_number",
  createdAt: "created_at",
  updatedAt: "updated_at",
  isActive: "is_active",
  medicineName_ar: "medicine_name_ar",
  medicineName_en: "medicine_name_en",
  subscriptionPlan: "subscription_plan",
  subscriptionStatus: "subscription_status",
  subscriptionStartedAt: "subscription_started_at",
  subscriptionEndsAt: "subscription_ends_at",
  subscriptionEndDate: "subscription_end_date",
  holdNumber: "hold_number",
  cartItems: "cart_items",
  createdBy: "created_by",
  createdByName: "created_by_name",
  refundMethod: "refund_method",
  isInstant: "is_instant",
  lowStockThreshold: "low_stock_threshold",
  expiringSoonDays: "expiring_soon_days",
  expiryNotifyEnabled: "expiry_notify_enabled",
  expiryNotifyPhone: "expiry_notify_phone",
  expiryNotifyEmail: "expiry_notify_email",
  payrollPayDay: "payroll_pay_day",
  payrollSickDeductionPercent: "payroll_sick_deduction_percent",
  payrollAbsentDeductionPercent: "payroll_absent_deduction_percent",
  payrollLeaveDeductionPercent: "payroll_leave_deduction_percent",
  payrollMaxLeaveDays: "payroll_max_leave_days",
  payrollStandardWorkHours: "payroll_standard_work_hours",
  payrollOvertimePercent: "payroll_overtime_percent",
  payrollWorkDayStart: "payroll_work_day_start",
  payrollWorkDayEnd: "payroll_work_day_end",
  payrollWorkBreaks: "payroll_work_breaks",
  workShifts: "work_shifts",
  defaultShiftId: "default_shift_id",
  assignedShiftId: "assigned_shift_id",
  shiftId: "shift_id",
  earlyLeaveOutcome: "early_leave_outcome",
  useCustomWorkSchedule: "use_custom_work_schedule",
  workDayStart: "work_day_start",
  workDayEnd: "work_day_end",
  workBreaks: "work_breaks",
  requestNumber: "request_number",
  pharmacyName: "pharmacy_name",
  requestedBy: "requested_by",
  requestedByName: "requested_by_name",
  reviewedBy: "reviewed_by",
  reviewedByName: "reviewed_by_name",
  reviewNote: "review_note",
  reviewedAt: "reviewed_at",
  employeeId: "employee_id",
  employeeCode: "employee_code",
  photoBase64: "photo_base64",
  requiredWorkHours: "required_work_hours",
  employeeName: "employee_name",
  jobTitle: "job_title",
  roleKey: "role_key",
  allowedPages: "allowed_pages",
  baseRole: "base_role",
  commissionRate: "commission_rate",
  hireDate: "hire_date",
  lastLoginAt: "last_login_at",
  requestType: "request_type",
  endDate: "end_date",
  requestedTime: "requested_time",
  baseSalary: "base_salary",
  workDate: "work_date",
  checkIn: "check_in",
  checkOut: "check_out",
  periodStart: "period_start",
  periodEnd: "period_end",
  workingDays: "working_days",
  presentDays: "present_days",
  absentDays: "absent_days",
  sickDays: "sick_days",
  leaveDays: "leave_days",
  workMinutes: "work_minutes",
  specialAllowances: "special_allowances",
  incentives: "incentives",
  commission: "commission",
  taxes: "taxes",
  insurance: "insurance",
  calculatedSalary: "calculated_salary",
  netPay: "net_pay",
  paidAt: "paid_at",
};

export function toCamelCase<T>(row: Record<string, any>): T {
  if (!row || typeof row !== "object") return row as T;

  return Object.entries(row).reduce(
    (acc, [key, value]) => {
      const camelKey = camelKeyMap[key] || key.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
      acc[camelKey] = value;
      return acc;
    },
    {} as Record<string, any>,
  ) as T;
}

export function toSnakeCase<T>(data: T): Record<string, any> {
  if (!data || typeof data !== "object") return data as unknown as Record<string, any>;

  return Object.entries(data as Record<string, any>).reduce(
    (acc, [key, value]) => {
      const snakeKey =
        snakeKeyMap[key] || key.replace(/([A-Z])/g, (match) => `_${match.toLowerCase()}`);
      acc[snakeKey] = value;
      return acc;
    },
    {} as Record<string, any>,
  );
}
