export type MigrationProbe =
  | { type: "table"; name: string }
  | { type: "column"; table: string; column: string }
  | { type: "rpc"; name: string; args?: Record<string, unknown> };

export type SqlMigrationGroup = "core" | "branches" | "pos" | "hr" | "saas";

export type SqlMigrationDefinition = {
  id: string;
  file: string;
  group: SqlMigrationGroup;
  titleAr: string;
  titleEn: string;
  noteAr?: string;
  noteEn?: string;
  probe: MigrationProbe;
};

export const SQL_MIGRATION_GROUPS: Record<SqlMigrationGroup, { labelAr: string; labelEn: string }> =
  {
    core: { labelAr: "الأساسيات", labelEn: "Core" },
    saas: { labelAr: "SaaS والاشتراك", labelEn: "SaaS & subscription" },
    branches: { labelAr: "الفروع والنقل", labelEn: "Branches & transfers" },
    pos: { labelAr: "نقطة البيع", labelEn: "Point of sale" },
    hr: { labelAr: "الموظفين والحضور", labelEn: "HR & attendance" },
  };

/** Recommended run order — newest features at the bottom. */
export const SQL_MIGRATIONS: SqlMigrationDefinition[] = [
  {
    id: "base-schema",
    file: "run-in-sql-editor.sql",
    group: "core",
    titleAr: "الجداول الأساسية والأعمدة",
    titleEn: "Base tables & columns",
    noteAr: "نقطة البداية لأي مشروع جديد أو بعد schema.sql",
    noteEn: "Starting point for new projects or after schema.sql",
    probe: { type: "table", name: "medicines" },
  },
  {
    id: "organizations",
    file: "multi-branch-organizations.sql",
    group: "core",
    titleAr: "مجموعات الفروع (organizations)",
    titleEn: "Branch organizations",
    noteAr: "بعد multi-tenant-saas.sql",
    noteEn: "Run after multi-tenant-saas.sql",
    probe: { type: "table", name: "organizations" },
  },
  {
    id: "branch-limit",
    file: "organization-branch-limit.sql",
    group: "saas",
    titleAr: "حد أقصى للفروع",
    titleEn: "Organization branch limit",
    probe: { type: "column", table: "pharmacies", column: "max_branches" },
  },
  {
    id: "branch-limit-rpc",
    file: "organization-branch-limit.sql",
    group: "saas",
    titleAr: "دالة set_organization_max_branches",
    titleEn: "set_organization_max_branches RPC",
    probe: { type: "rpc", name: "set_organization_max_branches", args: {} },
  },
  {
    id: "pharmacy-branch-insert-limit",
    file: "pharmacy-branch-insert-limit.sql",
    group: "saas",
    titleAr: "منع تجاوز حد المخازن (Trigger)",
    titleEn: "Warehouse branch insert limit trigger",
    noteAr: "بعد organization-branch-limit.sql — يمنع INSERT في pharmacies عند الوصول لـ max_branches",
    noteEn: "Run after organization-branch-limit.sql — blocks pharmacies INSERT at max_branches",
    probe: { type: "column", table: "pharmacies", column: "organization_id" },
  },
  {
    id: "subscription-tiers",
    file: "subscription-tiers.sql",
    group: "saas",
    titleAr: "باقات الاشتراك",
    titleEn: "Subscription tiers",
    noteAr: "بعد organization-branch-limit.sql",
    noteEn: "Run after organization-branch-limit.sql",
    probe: { type: "column", table: "pharmacies", column: "subscription_tier" },
  },
  {
    id: "user-limit",
    file: "organization-user-limit.sql",
    group: "saas",
    titleAr: "حد أقصى للمستخدمين",
    titleEn: "Organization user limit",
    noteAr: "بعد subscription-tiers.sql و pharmacy-custom-roles.sql",
    noteEn: "Run after subscription-tiers.sql and pharmacy-custom-roles.sql",
    probe: { type: "column", table: "pharmacies", column: "max_users" },
  },
  {
    id: "user-limit-rpc",
    file: "organization-user-limit.sql",
    group: "saas",
    titleAr: "دالة set_organization_max_users",
    titleEn: "set_organization_max_users RPC",
    probe: { type: "rpc", name: "set_organization_max_users", args: {} },
  },
  {
    id: "create-saas-pharmacy",
    file: "create-saas-pharmacy.sql",
    group: "saas",
    titleAr: "إنشاء صيدلية SaaS (Super Admin)",
    titleEn: "Create SaaS pharmacy (Super Admin)",
    noteAr: "يصلح خطأ «تعذر إنشاء الصيدلية» — شغّله قبل إضافة صيدليات جديدة",
    noteEn: "Fixes create-pharmacy failures — run before adding new pharmacies",
    probe: { type: "rpc", name: "create_saas_pharmacy", args: { p_id: "", p_name: "" } },
  },
  {
    id: "subscription-requests",
    file: "subscription-requests.sql",
    group: "saas",
    titleAr: "طلبات تجديد الاشتراك",
    titleEn: "Subscription requests",
    probe: { type: "table", name: "subscription_requests" },
  },
  {
    id: "subscription-tier-configs",
    file: "subscription-tier-configs.sql",
    group: "saas",
    titleAr: "إعدادات الباقات (قابلة للتعديل)",
    titleEn: "Editable subscription tier configs",
    noteAr: "بعد subscription-tiers.sql — يسمح لمالك النظام بتعديل حدود ومميزات الباقات",
    noteEn: "Run after subscription-tiers.sql — lets the system owner edit tier limits and features",
    probe: { type: "table", name: "subscription_tier_configs" },
  },
  {
    id: "trial-signup",
    file: "trial-signup.sql",
    group: "saas",
    titleAr: "تسجيل تجريبي 14 يوم",
    titleEn: "14-day trial signup",
    probe: { type: "rpc", name: "provision_trial_pharmacy", args: { p_pharmacy_name: "" } },
  },
  {
    id: "medicine-active-ingredient",
    file: "medicine-active-ingredient.sql",
    group: "core",
    titleAr: "المادة الفعالة للأدوية",
    titleEn: "Medicine active ingredient",
    noteAr: "للبحث في المخزون بالمادة الفعالة — شغّله بعد run-in-sql-editor.sql",
    noteEn: "Enables inventory search by active ingredient — run after run-in-sql-editor.sql",
    probe: { type: "column", table: "medicines", column: "active_ingredient" },
  },
  {
    id: "medicine-catalog-import",
    file: "medicine-catalog-import.sql",
    group: "core",
    titleAr: "استيراد كatalog الأدوية",
    titleEn: "Medicine catalog import",
    noteAr: "حذف واستبدال قائمة الأدوية + إدراج دفعات — بعد complete-sale-rpc.sql",
    noteEn: "Replace medicine catalog and batch insert — run after complete-sale-rpc.sql",
    probe: { type: "rpc", name: "import_medicine_catalog_batch", args: {} },
  },
  {
    id: "medicine-catalog-reference",
    file: "medicine-catalog-reference.sql",
    group: "core",
    titleAr: "كتالوج مركزي + CSV",
    titleEn: "Central catalog + CSV",
    noteAr: "الكتالوج المركزي لـ Victory — استيراد + تحديث مع الحفاظ على الكميات",
    noteEn: "Central Victory catalog — import + sync preserving stock",
    probe: { type: "rpc", name: "sync_pharmacy_from_catalog_reference", args: {} },
  },
  {
    id: "complete-sale-rpc",
    file: "complete-sale-rpc.sql",
    group: "pos",
    titleAr: "بيع مع خصم المخزون (RPC)",
    titleEn: "Sale with stock deduction (RPC)",
    probe: { type: "rpc", name: "complete_sale_with_stock_deduction", args: {} },
  },
  {
    id: "complete-purchase-rpc",
    file: "complete-purchase-rpc.sql",
    group: "pos",
    titleAr: "توريد مع إضافة المخزون (RPC)",
    titleEn: "Purchase with stock addition (RPC)",
    probe: { type: "rpc", name: "complete_purchase_with_stock_addition", args: {} },
  },
  {
    id: "branch-transfers",
    file: "branch-stock-transfers.sql",
    group: "branches",
    titleAr: "نقل مخزون بين الفروع",
    titleEn: "Branch stock transfers",
    probe: { type: "table", name: "branch_stock_transfers" },
  },
  {
    id: "branch-transfer-batch-rpc",
    file: "branch-transfer-batch-rpc.sql",
    group: "branches",
    titleAr: "دفعة نقل مخزون (RPC)",
    titleEn: "Branch transfer batch (RPC)",
    probe: { type: "rpc", name: "execute_branch_stock_transfer_batch", args: {} },
  },
  {
    id: "cashier-shifts",
    file: "cashier-shifts.sql",
    group: "pos",
    titleAr: "ورديات الكاشير",
    titleEn: "Cashier shifts",
    noteAr: "بعد complete-sale-rpc.sql",
    noteEn: "Run after complete-sale-rpc.sql",
    probe: { type: "table", name: "cashier_shifts" },
  },
  {
    id: "held-invoices",
    file: "held-invoices-and-instant-return.sql",
    group: "pos",
    titleAr: "الفواتير المعلقة والمرتجع السريع",
    titleEn: "Held invoices & quick return",
    probe: { type: "table", name: "held_invoices" },
  },
  {
    id: "pharmacy-costs",
    file: "add-pharmacy-costs.sql",
    group: "core",
    titleAr: "تكاليف الصيدلية",
    titleEn: "Pharmacy costs",
    probe: { type: "table", name: "pharmacy_costs" },
  },
  {
    id: "login-accounts",
    file: "pharmacy-login-accounts.sql",
    group: "saas",
    titleAr: "حسابات دخول الصيدلية",
    titleEn: "Pharmacy login accounts",
    probe: { type: "table", name: "pharmacy_login_accounts" },
  },
  {
    id: "auth-catalog-sync",
    file: "auth-user-login-catalog-sync.sql",
    group: "saas",
    titleAr: "مزامنة Auth مع حسابات الدخول",
    titleEn: "Auth → login catalog sync",
    probe: { type: "column", table: "pharmacy_login_accounts", column: "review_note" },
  },
  {
    id: "employees",
    file: "employees-users-migration.sql",
    group: "hr",
    titleAr: "جدول الموظفين",
    titleEn: "Employees table",
    probe: { type: "table", name: "employees" },
  },
  {
    id: "attendance",
    file: "attendance-payroll.sql",
    group: "hr",
    titleAr: "الحضور والمرتبات",
    titleEn: "Attendance & payroll",
    probe: { type: "table", name: "attendance_records" },
  },
  {
    id: "secure-attendance-geofence",
    file: "secure-attendance-geofence.sql",
    group: "hr",
    titleAr: "حضور آمن (QR + GPS)",
    titleEn: "Secure attendance (QR + GPS)",
    noteAr: "بعد attendance-self-checkin-rls.sql — QR متغير + تحقق الموقع",
    noteEn: "Run after attendance-self-checkin-rls.sql — rotating QR + geofence",
    probe: { type: "rpc", name: "process_secure_attendance", args: {} },
  },
  {
    id: "attendance-qr-ttl-10s",
    file: "attendance-qr-ttl-10s.sql",
    group: "hr",
    titleAr: "QR حضور — صلاحية 10 ثوانٍ",
    titleEn: "Attendance QR — 10 second TTL",
    noteAr: "بعد secure-attendance-geofence.sql — يقلّل مدة صلاحية الرمز إلى 10 ثوانٍ",
    noteEn: "Run after secure-attendance-geofence.sql — reduces QR token TTL to 10 seconds",
    probe: { type: "rpc", name: "build_attendance_qr_token", args: { p_pharmacy_id: "main" } },
  },
  {
    id: "attendance-self-checkin",
    file: "attendance-self-checkin-rls.sql",
    group: "hr",
    titleAr: "تسجيل حضور الموظف (بوابة حضوري)",
    titleEn: "Employee self check-in (portal)",
    noteAr: "بعد org-hr-access.sql — يسمح للموظف بتسجيل حضوره وانصرافه",
    noteEn: "Run after org-hr-access.sql — lets employees clock in/out from the portal",
    probe: { type: "rpc", name: "is_own_attendance_user", args: { p_user_id: "" } },
  },
  {
    id: "session-revoke",
    file: "user-session-revocation.sql",
    group: "saas",
    titleAr: "إلغاء جلسة المستخدم",
    titleEn: "User session revocation",
    probe: { type: "rpc", name: "revoke_user_app_access", args: {} },
  },
  {
    id: "expiry-notify",
    file: "expiry-notify.sql",
    group: "core",
    titleAr: "تنبيهات انتهاء الصلاحية",
    titleEn: "Expiry notifications",
    probe: { type: "column", table: "pharmacies", column: "expiry_notify_enabled" },
  },
  {
    id: "custom-roles",
    file: "pharmacy-custom-roles.sql",
    group: "hr",
    titleAr: "أدوار مخصصة للصيدلية",
    titleEn: "Pharmacy custom roles",
    probe: { type: "table", name: "pharmacy_custom_roles" },
  },
  {
    id: "role-configs",
    file: "pharmacy-role-configs.sql",
    group: "hr",
    titleAr: "تخصيص صلاحيات الأدوار",
    titleEn: "Role permission overrides",
    probe: { type: "table", name: "pharmacy_role_configs" },
  },
  {
    id: "delete-pharmacy-cascade",
    file: "delete-pharmacy-cascade.sql",
    group: "saas",
    titleAr: "حذف الصيدلية مع البيانات المرتبطة",
    titleEn: "Cascade pharmacy delete",
    noteAr: "مطلوب لزر حذف الصيدلية في لوحة SaaS",
    noteEn: "Required for the SaaS admin delete button",
    probe: { type: "rpc", name: "delete_pharmacy_cascade", args: { p_pharmacy_id: "__probe__" } },
  },
  {
    id: "fix-admin-login",
    file: "fix-admin-login-now.sql",
    group: "core",
    titleAr: "إصلاح تسجيل الدخول (بدون Edge Function)",
    titleEn: "Fix login (no Edge Function required)",
    noteAr: "شغّله وضع JWT Secret من Settings → API ثم جرّب admin@pharmacy.com",
    noteEn: "Run and paste JWT Secret from Settings → API then try admin@pharmacy.com",
    probe: { type: "rpc", name: "app_client_login", args: {} },
  },
  {
    id: "custom-app-auth",
    file: "custom-app-auth.sql",
    group: "core",
    titleAr: "مصادقة التطبيق (إيميل + كلمة مرور)",
    titleEn: "App authentication (email + password)",
    noteAr: "يستبدل Supabase Auth — شغّله ثم انشر Edge Function app-auth وعيّن كلمة مرور المالك",
    noteEn: "Replaces Supabase Auth — run then deploy app-auth edge function and set owner password",
    probe: { type: "column", table: "users", column: "password_hash" },
  },
  {
    id: "fix-trial-registration",
    file: "fix-trial-registration.sql",
    group: "core",
    titleAr: "إصلاح تسجيل صيدلية جديدة (نسخة تجربة)",
    titleEn: "Fix new pharmacy trial signup",
    noteAr: "يصلح خطأ «غير مصرح بهذا الإجراء» عند «ابدأ التجربة المجانية»",
    noteEn: "Fixes «Not authorized» when starting a free trial from the login page",
    probe: { type: "rpc", name: "register_trial_app_user", args: {} },
  },
  {
    id: "subscription-tier-package-price",
    file: "subscription-tier-package-price.sql",
    group: "core",
    titleAr: "سعر الباقة الشهري",
    titleEn: "Monthly package price",
    noteAr: "بعد subscription-tier-configs.sql — يخزّن سعر كل باقة شهرياً",
    noteEn: "Run after subscription-tier-configs.sql — stores monthly price per package",
    probe: { type: "column", table: "subscription_tier_configs", column: "package_price" },
  },
  {
    id: "subscription-tier-pages",
    file: "subscription-tier-pages.sql",
    group: "core",
    titleAr: "صفحات الباقة (فتح/إغلاق)",
    titleEn: "Package page access toggles",
    noteAr: "بعد subscription-tier-configs.sql — يخزّن الصفحات المفعّلة لكل باقة",
    noteEn: "Run after subscription-tier-configs.sql — stores enabled pages per package",
    probe: { type: "column", table: "subscription_tier_configs", column: "enabled_pages" },
  },
  {
    id: "subscription-feature-gating",
    file: "subscription-feature-gating.sql",
    group: "core",
    titleAr: "Feature Gating ديناميكي (صفحات + ميزات)",
    titleEn: "Dynamic feature gating (routes + features)",
    noteAr: "بعد subscription-tier-configs.sql — يضيف enabled_pages و package_price و allowed_features + view plans_config",
    noteEn: "Run after subscription-tier-configs.sql — adds enabled_pages, package_price, allowed_features + plans_config view",
    probe: { type: "column", table: "subscription_tier_configs", column: "allowed_features" },
  },
  {
    id: "reset-owner-login",
    file: "reset-owner-login.sql",
    group: "core",
    titleAr: "إعادة ضبط دخول مالك النظام",
    titleEn: "Reset system owner login",
    noteAr: "admin@victory.com / Mn01125526012# — الصق JWT Secret ثم شغّل الملف",
    noteEn: "admin@victory.com / Mn01125526012# — paste JWT Secret then run",
    probe: { type: "rpc", name: "app_client_login", args: {} },
  },
  {
    id: "fix-employees-rls-pharmacy-admin",
    file: "fix-employees-rls-pharmacy-admin.sql",
    group: "core",
    titleAr: "إصلاح إضافة موظفين (مدير التجربة)",
    titleEn: "Fix employee insert for trial pharmacy_admin",
    noteAr: "يصلح is_active_user للتجربة + RLS جدول employees",
    noteEn: "Fixes is_active_user for trial + employees RLS",
    probe: { type: "table", name: "employees" },
  },
  {
    id: "customers-crm",
    file: "customers-crm.sql",
    group: "core",
    titleAr: "CRM العملاء (ملفات + متابعات)",
    titleEn: "Customer CRM (profiles + follow-ups)",
    noteAr: "بعد run-in-sql-editor.sql — يفعّل تبويب CRM في العملاء",
    noteEn: "Run after run-in-sql-editor.sql — enables CRM tab on Customers page",
    probe: { type: "table", name: "customer_activities" },
  },
  {
    id: "clear-all-medicines",
    file: "clear-all-medicines.sql",
    group: "core",
    titleAr: "مسح كل بيانات الأدوية",
    titleEn: "Clear all medicine data",
    noteAr: "قبل استيراد كatalog جديد — يحذف medicines + catalog_reference + movements",
    noteEn: "Before new catalog import — deletes medicines + catalog_reference + movements",
    probe: { type: "table", name: "medicines" },
  },
  {
    id: "apply-urgent-priority",
    file: "apply-urgent-priority.sql",
    group: "core",
    titleAr: "الأولويات العاجلة (دليل + إصلاح trial)",
    titleEn: "Urgent priority bundle (guide + trial fix)",
    noteAr: "يشغّل إصلاح التجربة + قائمة الملفات المتبقية بالترتيب",
    noteEn: "Runs trial fix + ordered checklist of remaining migrations",
    probe: { type: "table", name: "employees" },
  },
  {
    id: "fix-delete-pharmacy-user",
    file: "fix-delete-pharmacy-user.sql",
    group: "core",
    titleAr: "إصلاح حذف مستخدمي الصيدلية",
    titleEn: "Fix deleting pharmacy login users",
    noteAr: "يسمح لمالك النظام/مدير الصيدلية بحذف حسابات الدخول",
    noteEn: "Allows system owner / pharmacy manager to delete login accounts",
    probe: { type: "rpc", name: "revoke_user_app_access", args: {} },
  },
];
