import type { SqlMigrationDefinition } from "./sqlMigrationTypes";

/** Previously untracked SQL files — appended to SQL_MIGRATIONS for in-app status probes. */
export const SQL_MIGRATION_EXTRA_ENTRIES: SqlMigrationDefinition[] = [
  {
    id: "schema-bootstrap",
    file: "schema.sql",
    group: "core",
    titleAr: "Schema قديم (bootstrap)",
    titleEn: "Legacy schema bootstrap",
    noteAr: "مشاريع جديدة — prefer setup-complete.sql",
    noteEn: "New projects — prefer setup-complete.sql",
    probe: { type: "table", name: "medicines" },
  },
  {
    id: "setup-complete",
    file: "setup-complete.sql",
    group: "core",
    titleAr: "إعداد Supabase الكامل",
    titleEn: "Full Supabase setup bundle",
    noteAr: "نقطة بداية مشروع جديد — قبل multi-tenant-saas.sql",
    noteEn: "New project entry point — before multi-tenant-saas.sql",
    probe: { type: "table", name: "users" },
  },
  {
    id: "multi-tenant-saas",
    file: "multi-tenant-saas.sql",
    group: "saas",
    titleAr: "أساس SaaS متعدد المستأجرين",
    titleEn: "Multi-tenant SaaS foundation",
    noteAr: "بعد setup-complete.sql — pharmacies + RLS أساسي",
    noteEn: "Run after setup-complete.sql — pharmacies + base RLS",
    probe: { type: "table", name: "pharmacies" },
  },
  {
    id: "branches-multi",
    file: "branches-multi.sql",
    group: "branches",
    titleAr: "فروع متعددة (legacy)",
    titleEn: "Multi-branch (legacy)",
    noteAr: "قبل multi-branch-organizations.sql إن وُجد",
    noteEn: "Before multi-branch-organizations.sql if needed",
    probe: { type: "column", table: "pharmacies", column: "organization_id" },
  },
  {
    id: "accountant-org-read",
    file: "accountant-org-read.sql",
    group: "core",
    titleAr: "قراءة المحاسب لكل الفروع",
    titleEn: "Accountant org-wide read access",
    noteAr: "بعد multi-tenant-saas.sql — قبل org-hr-access.sql",
    noteEn: "After multi-tenant-saas.sql — before org-hr-access.sql",
    probe: { type: "rpc", name: "is_accountant", args: {} },
  },
  {
    id: "org-hr-access",
    file: "org-hr-access.sql",
    group: "hr",
    titleAr: "HR على مستوى المجموعة",
    titleEn: "Organization-wide HR access",
    noteAr: "بعد accountant-org-read.sql",
    noteEn: "Run after accountant-org-read.sql",
    probe: { type: "rpc", name: "can_read_pharmacy_row", args: { row_pharmacy_id: "main" } },
  },
  {
    id: "org-login-accounts-access",
    file: "org-login-accounts-access.sql",
    group: "saas",
    titleAr: "حسابات الدخول على مستوى المجموعة",
    titleEn: "Organization login accounts access",
    noteAr: "بعد pharmacy-login-accounts.sql",
    noteEn: "Run after pharmacy-login-accounts.sql",
    probe: { type: "table", name: "pharmacy_login_accounts" },
  },
  {
    id: "secure-rls",
    file: "secure-rls.sql",
    group: "core",
    titleAr: "RLS آمن (نسخة مبكرة)",
    titleEn: "Secure RLS (early bundle)",
    noteAr: "للترقية — prefer rls-security-hardening.sql",
    noteEn: "Legacy upgrade path — prefer rls-security-hardening.sql",
    probe: { type: "table", name: "medicines" },
  },
  {
    id: "public-signup",
    file: "public-signup.sql",
    group: "saas",
    titleAr: "تسجيل عام (legacy)",
    titleEn: "Public signup (legacy)",
    probe: { type: "rpc", name: "provision_trial_pharmacy", args: { p_pharmacy_name: "" } },
  },
  {
    id: "username-login",
    file: "username-login.sql",
    group: "core",
    titleAr: "دخول باسم المستخدم",
    titleEn: "Username login resolver",
    noteAr: "بعد custom-app-auth.sql",
    noteEn: "Run after custom-app-auth.sql",
    probe: { type: "rpc", name: "resolve_login_email", args: { login_identifier: "" } },
  },
  {
    id: "fix-jwt-encoding",
    file: "fix-jwt-encoding.sql",
    group: "core",
    titleAr: "إصلاح ترميز JWT",
    titleEn: "Fix JWT encoding",
    noteAr: "بعد custom-app-auth.sql — الصق JWT Secret",
    noteEn: "After custom-app-auth.sql — paste JWT Secret",
    probe: { type: "rpc", name: "sign_app_access_token", args: {} },
  },
  {
    id: "login-account-requests",
    file: "login-account-requests.sql",
    group: "saas",
    titleAr: "طلبات حسابات الدخول",
    titleEn: "Login account requests",
    probe: { type: "table", name: "login_account_requests" },
  },
  {
    id: "alter-login-account-requests-password",
    file: "alter-login-account-requests-password.sql",
    group: "saas",
    titleAr: "كلمة مرور طلبات الحساب",
    titleEn: "Login request password column",
    probe: { type: "column", table: "login_account_requests", column: "password_hash" },
  },
  {
    id: "alter-pharmacy-login-accounts-status",
    file: "alter-pharmacy-login-accounts-status.sql",
    group: "saas",
    titleAr: "حالة حسابات الدخول",
    titleEn: "Login account status column",
    probe: { type: "column", table: "pharmacy_login_accounts", column: "status" },
  },
  {
    id: "alter-pharmacy-login-accounts-link-request",
    file: "alter-pharmacy-login-accounts-link-request.sql",
    group: "saas",
    titleAr: "ربط الحساب بطلب الدخول",
    titleEn: "Link login account to request",
    probe: { type: "column", table: "pharmacy_login_accounts", column: "login_request_id" },
  },
  {
    id: "alter-pharmacy-login-accounts-pending-edit",
    file: "alter-pharmacy-login-accounts-pending-edit.sql",
    group: "saas",
    titleAr: "تعديلات حسابات معلّقة",
    titleEn: "Pending login account edits",
    probe: { type: "column", table: "pharmacy_login_accounts", column: "pending_password" },
  },
  {
    id: "fix-login-account-requests-visibility",
    file: "fix-login-account-requests-visibility.sql",
    group: "saas",
    titleAr: "إصلاح ظهور طلبات الحساب",
    titleEn: "Fix login request visibility RLS",
    probe: { type: "table", name: "login_account_requests" },
  },
  {
    id: "fix-login-account-role-sync",
    file: "fix-login-account-role-sync.sql",
    group: "saas",
    titleAr: "مزامنة دور حساب الدخول",
    titleEn: "Login account role sync",
    probe: { type: "table", name: "pharmacy_login_accounts" },
  },
  {
    id: "sync-login-account-users",
    file: "sync-login-account-users.sql",
    group: "saas",
    titleAr: "مزامنة users ↔ login accounts",
    titleEn: "Sync users ↔ login accounts",
    probe: { type: "table", name: "pharmacy_login_accounts" },
  },
  {
    id: "subscription-request-notify",
    file: "subscription-request-notify.sql",
    group: "saas",
    titleAr: "إشعار طلبات الاشتراك (webhook)",
    titleEn: "Subscription request webhook notify",
    probe: { type: "table", name: "subscription_requests" },
  },
  {
    id: "fix-super-admin-subscription-approve",
    file: "fix-super-admin-subscription-approve.sql",
    group: "saas",
    titleAr: "إصلاح اعتماد الاشتراك (Super Admin)",
    titleEn: "Fix super admin subscription approve",
    probe: { type: "table", name: "subscription_requests" },
  },
  {
    id: "manual-user-provisioning",
    file: "manual-user-provisioning.sql",
    group: "core",
    titleAr: "تجهيز مستخدم يدوي",
    titleEn: "Manual user provisioning",
    noteAr: "Ops — إنشاء admin يدوياً",
    noteEn: "Ops — manual admin bootstrap",
    probe: { type: "table", name: "users" },
  },
  {
    id: "branch-manager-role",
    file: "branch-manager-role.sql",
    group: "branches",
    titleAr: "دور مدير الفرع",
    titleEn: "Branch manager role",
    probe: { type: "table", name: "users" },
  },
  {
    id: "branch-transfer-approval",
    file: "branch-transfer-approval.sql",
    group: "branches",
    titleAr: "اعتماد نقل المخزون",
    titleEn: "Branch transfer approval workflow",
    probe: { type: "column", table: "branch_stock_transfers", column: "status" },
  },
  {
    id: "fix-branch-manager-sync",
    file: "fix-branch-manager-sync.sql",
    group: "branches",
    titleAr: "إصلاح مزامنة مدير الفرع",
    titleEn: "Fix branch manager sync",
    probe: { type: "table", name: "users" },
  },
  {
    id: "fix-medicine-barcode-per-pharmacy",
    file: "fix-medicine-barcode-per-pharmacy.sql",
    group: "core",
    titleAr: "باركود فريد لكل صيدلية",
    titleEn: "Barcode unique per pharmacy",
    probe: { type: "column", table: "medicines", column: "pharmacy_id" },
  },
  {
    id: "fix-missing-columns",
    file: "fix-missing-columns.sql",
    group: "core",
    titleAr: "أعمدة ناقصة (hotfix)",
    titleEn: "Missing columns hotfix",
    probe: { type: "table", name: "medicines" },
  },
  {
    id: "medicines-search-trgm-index",
    file: "medicines-search-trgm-index.sql",
    group: "core",
    titleAr: "فهرس بحث TRGM للمخزون",
    titleEn: "TRGM search index for inventory",
    noteAr: "بعد medicine-active-ingredient.sql — للكتalogات الكبيرة",
    noteEn: "After medicine-active-ingredient.sql — large catalogs",
    probe: { type: "column", table: "medicines", column: "active_ingredient" },
  },
  {
    id: "add-purchases-columns",
    file: "add-purchases-columns.sql",
    group: "pos",
    titleAr: "أعمدة المشتريات",
    titleEn: "Purchases table columns",
    probe: { type: "table", name: "purchases" },
  },
  {
    id: "fix-purchases-complete",
    file: "fix-purchases-complete.sql",
    group: "pos",
    titleAr: "إصلاح المشتريات + RPC",
    titleEn: "Fix purchases + RPC",
    probe: { type: "rpc", name: "complete_purchase_with_stock_addition", args: {} },
  },
  {
    id: "fix-purchase-number-unique",
    file: "fix-purchase-number-unique.sql",
    group: "pos",
    titleAr: "رقم شراء فريد",
    titleEn: "Unique purchase number",
    probe: { type: "table", name: "purchases" },
  },
  {
    id: "drop-inventory-cost-profit-password",
    file: "drop-inventory-cost-profit-password.sql",
    group: "core",
    titleAr: "إزالة كلمة مرور تكلفة المخزون",
    titleEn: "Drop inventory cost password RPC",
    noteAr: "تنظيف — استُبدل بصلاحيات الأدوار",
    noteEn: "Cleanup — replaced by role permissions",
    probe: { type: "column", table: "pharmacies", column: "payroll_pay_day" },
  },
  {
    id: "create-employees-table-only",
    file: "create-employees-table-only.sql",
    group: "hr",
    titleAr: "جدول employees فقط",
    titleEn: "Employees table only",
    noteAr: "بديل employees-users-migration.sql",
    noteEn: "Alternative to employees-users-migration.sql",
    probe: { type: "table", name: "employees" },
  },
  {
    id: "add-employee-code",
    file: "add-employee-code.sql",
    group: "hr",
    titleAr: "كود الموظف",
    titleEn: "Employee code column",
    probe: { type: "column", table: "employees", column: "employee_code" },
  },
  {
    id: "add-employee-photo",
    file: "add-employee-photo.sql",
    group: "hr",
    titleAr: "صورة الموظف",
    titleEn: "Employee photo column",
    probe: { type: "column", table: "employees", column: "photo_base64" },
  },
  {
    id: "add-employee-requests",
    file: "add-employee-requests.sql",
    group: "hr",
    titleAr: "طلبات الموظفين (إجازة/سلف)",
    titleEn: "Employee requests (leave/advance)",
    probe: { type: "table", name: "employee_requests" },
  },
  {
    id: "add-required-work-hours",
    file: "add-required-work-hours.sql",
    group: "hr",
    titleAr: "ساعات العمل المطلوبة",
    titleEn: "Required work hours column",
    probe: { type: "column", table: "employees", column: "required_work_hours" },
  },
  {
    id: "rename-pharmacy-admin-to-admin",
    file: "rename-pharmacy-admin-to-admin.sql",
    group: "hr",
    titleAr: "تسمية pharmacy_admin → admin",
    titleEn: "Rename pharmacy_admin role to admin",
    probe: { type: "table", name: "users" },
  },
  {
    id: "fix-users-role-check",
    file: "fix-users-role-check.sql",
    group: "hr",
    titleAr: "إصلاح constraint أدوار users",
    titleEn: "Fix users role check constraint",
    probe: { type: "table", name: "users" },
  },
  {
    id: "add-payroll-columns",
    file: "add-payroll-columns.sql",
    group: "hr",
    titleAr: "أعمدة سجل المرتبات",
    titleEn: "Payroll records columns",
    probe: { type: "table", name: "payroll_records" },
  },
  {
    id: "add-payroll-settings",
    file: "add-payroll-settings.sql",
    group: "hr",
    titleAr: "إعدادات المرتبات",
    titleEn: "Payroll settings on pharmacies",
    probe: { type: "column", table: "pharmacies", column: "payroll_pay_day" },
  },
  {
    id: "add-payroll-overtime-settings",
    file: "add-payroll-overtime-settings.sql",
    group: "hr",
    titleAr: "إعدادات overtime",
    titleEn: "Payroll overtime settings",
    probe: { type: "column", table: "pharmacies", column: "payroll_overtime_percent" },
  },
  {
    id: "add-payroll-taxes-insurance-settings",
    file: "add-payroll-taxes-insurance-settings.sql",
    group: "hr",
    titleAr: "ضرائب وتأمينات المرتبات",
    titleEn: "Payroll tax & insurance settings",
    probe: { type: "column", table: "pharmacies", column: "payroll_default_taxes" },
  },
  {
    id: "add-payroll-max-leave-days",
    file: "add-payroll-max-leave-days.sql",
    group: "hr",
    titleAr: "حد أيام الإجازة",
    titleEn: "Max leave days setting",
    probe: { type: "column", table: "pharmacies", column: "payroll_max_leave_days" },
  },
  {
    id: "fix-payroll-defaults",
    file: "fix-payroll-defaults.sql",
    group: "hr",
    titleAr: "قيم افتراضية للمرتبات",
    titleEn: "Payroll default values fix",
    probe: { type: "table", name: "payroll_records" },
  },
  {
    id: "add-pharmacy-shifts",
    file: "add-pharmacy-shifts.sql",
    group: "hr",
    titleAr: "ورديات العمل",
    titleEn: "Work shifts configuration",
    probe: { type: "column", table: "pharmacies", column: "work_shifts" },
  },
  {
    id: "add-work-schedule-settings",
    file: "add-work-schedule-settings.sql",
    group: "hr",
    titleAr: "جدول العمل الأسبوعي",
    titleEn: "Weekly work schedule settings",
    probe: { type: "column", table: "pharmacies", column: "work_schedule" },
  },
  {
    id: "add-shift-late-grace",
    file: "add-shift-late-grace.sql",
    group: "hr",
    titleAr: "فترة سماح التأخير",
    titleEn: "Shift late grace minutes",
    probe: { type: "column", table: "pharmacies", column: "shift_late_grace_minutes" },
  },
  {
    id: "alter-attendance-early-leave-outcome",
    file: "alter-attendance-early-leave-outcome.sql",
    group: "hr",
    titleAr: "نتيجة الانصراف المبكر",
    titleEn: "Early leave attendance outcome",
    probe: { type: "column", table: "attendance_records", column: "early_leave_outcome" },
  },
  {
    id: "attendance-qr-display-permission",
    file: "attendance-qr-display-permission.sql",
    group: "hr",
    titleAr: "صلاحية عرض QR الحضور",
    titleEn: "Attendance QR display permission",
    probe: { type: "rpc", name: "build_attendance_qr_token", args: { p_pharmacy_id: "main" } },
  },
  {
    id: "rls-security-audit-fixes",
    file: "rls-security-audit-fixes.sql",
    group: "core",
    titleAr: "إصلاحات مراجعة RLS",
    titleEn: "RLS audit fixes",
    noteAr: "بعد rls-security-hardening.sql",
    noteEn: "Run after rls-security-hardening.sql",
    probe: { type: "table", name: "customers" },
  },
];
